"""Add thumbnail_filename column to Photo model

Revision ID: 37a714659555
Revises: c6b8f0675dde
Create Date: 2025-04-13 20:04:07.535557

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '37a714659555'
down_revision = 'c6b8f0675dde'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('photo', schema=None) as batch_op:
        batch_op.add_column(sa.Column('thumbnail_filename', sa.String(length=100), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('photo', schema=None) as batch_op:
        batch_op.drop_column('thumbnail_filename')

    # ### end Alembic commands ###
