"""Add status, deadline and client info to Project model

Revision ID: 7a0b7678de8e
Revises: f04917d29afc
Create Date: 2025-04-14 19:11:02.032596

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7a0b7678de8e'
down_revision = 'f04917d29afc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('project', schema=None) as batch_op:
        batch_op.add_column(sa.Column('status', sa.String(length=20), nullable=True))
        batch_op.add_column(sa.Column('deadline', sa.Date(), nullable=True))
        batch_op.add_column(sa.Column('client_name', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('client_email', sa.String(length=120), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('project', schema=None) as batch_op:
        batch_op.drop_column('client_email')
        batch_op.drop_column('client_name')
        batch_op.drop_column('deadline')
        batch_op.drop_column('status')

    # ### end Alembic commands ###
