"""Add delivery_method to Selection model

Revision ID: acc01848c90a
Revises: 37a714659555
Create Date: 2025-04-14 11:25:42.155260

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'acc01848c90a'
down_revision = '37a714659555'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('selection', schema=None) as batch_op:
        batch_op.add_column(sa.Column('delivery_method', sa.String(length=10), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('selection', schema=None) as batch_op:
        batch_op.drop_column('delivery_method')

    # ### end Alembic commands ###
