"""Add Google Drive integration fields

Revision ID: b17823c42f65
Revises: 7a0b7678de8e
Create Date: 2025-04-17 19:01:53.294353

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b17823c42f65'
down_revision = '7a0b7678de8e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('photo', schema=None) as batch_op:
        batch_op.add_column(sa.Column('drive_file_id', sa.String(length=120), nullable=True))

    with op.batch_alter_table('project', schema=None) as batch_op:
        batch_op.add_column(sa.Column('drive_folder_id', sa.String(length=120), nullable=True))

    with op.batch_alter_table('selection', schema=None) as batch_op:
        batch_op.alter_column('email',
               existing_type=sa.VARCHAR(length=120),
               type_=sa.String(length=100),
               existing_nullable=True)
        batch_op.alter_column('delivery_method',
               existing_type=sa.VARCHAR(length=10),
               type_=sa.String(length=20),
               nullable=False)
        batch_op.drop_index('idx_selection_share_key')
        batch_op.create_unique_constraint(None, ['share_key'])
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(None, 'project', ['project_id'], ['id'], ondelete='CASCADE')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('selection', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(None, 'project', ['project_id'], ['id'])
        batch_op.drop_constraint(None, type_='unique')
        batch_op.create_index('idx_selection_share_key', ['share_key'], unique=False)
        batch_op.alter_column('delivery_method',
               existing_type=sa.String(length=20),
               type_=sa.VARCHAR(length=10),
               nullable=True)
        batch_op.alter_column('email',
               existing_type=sa.String(length=100),
               type_=sa.VARCHAR(length=120),
               existing_nullable=True)

    with op.batch_alter_table('project', schema=None) as batch_op:
        batch_op.drop_column('drive_folder_id')

    with op.batch_alter_table('photo', schema=None) as batch_op:
        batch_op.drop_column('drive_file_id')

    # ### end Alembic commands ###
